# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: CS3217
tagline: "Personal Statement"
description: "Personal Statement"
baseurl: ""
url: https://jasonqiu212.github.io/cs3217-personal-statement/

author:
  name: "Jason Qiu"

github:
  repo: https://github.com/jasonqiu212/cs3217-personal-statement
