# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: CS3217
tagline: "Personal Statement"
description: "Personal Statement"
baseurl: /

author:
  name: "Jason Qiu"

github: https://github.com/jasonqiu212
